dist: trusty
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
after_success:
  - npm run coveralls
  - npm run prepare
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    on:
      tags: true
      condition: ($TRAVIS_TAG =~ ^v[0-9]+(\.[0-9]+)*$)
